apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aismv-misc-m2cache
  namespace: aismv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-core
