apiVersion: apps/v1
kind: Deployment
metadata:
  name: aismv-router-eds
  namespace: aismv
  labels:
    app: aismv-router-eds
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: aismv-router-eds
  template:
    metadata:
      labels:
        app: aismv-router-eds
    spec:
      containers:
      - image: 172.16.9.49:30020/aismv/router/aismv-router-eds:$BUILD_NUMBER
        name: aismv-router-eds
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: aismv-router-eds
  namespace: aismv
spec:
  type: NodePort
  selector:
    app: aismv-router-eds
  ports:
  - nodePort: 31108
    protocol: TCP
    port: 8080
    targetPort: 8080